# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 634f4eb3c3d003fc67f842955cd148fc5e9dbc65bbb7edc57a69ff33bb884bcf50fb82109d758ec88c73df3b13acf271417c2570d44fe455b321f105aa979599

test:
  secret_key_base: 2bf7c71d8537064ec5efc20ef205e44519843b34da670cde4d87ea452e05b6cc40975d87a91146dd0ab628326a9ae9719f20eef46a72fd66e1658fc04473919b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
